apiVersion: v1
kind: Pod
metadata:
  name: clamb
spec:
  containers:
  - name: clamb
    image: tiredofit/clamav:2.5.3
    ports:
    - containerPort: 9009
    volumeMounts:
    - name: volumea
      mountPath: /scana
  volumes:
   - name: volumea
     persistentVolumeClaim:
       claimName: test-pvc