apiVersion: v1
kind: Pod
metadata:
  name: clamav3
spec:
  containers:
  - image: tiredofit/clamav:2.5.3
    name: clamav
    ports:
    - containerPort: 9009
    volumeMounts:
      mountPath: /mnt
      name: logs-volume
  volumes:
  - hostPath:
      path: /home/fxtadmin/fred_test
      type: Directory
    name: logs-volume1
