apiVersion: v1
kind: Pod
metadata:
  name: clamav3
spec:
  containers:
  - image: tiredofit/clamav:2.5.3
    name: clamav3
    ports:
    - containerPort: 9009
    volumeMounts:
    - mountPath: /mnt
      name: logs-volume
  volumes:
  - name: logs-volume
    persistentVolumeClaim:
      claimName: antivirus-pvc
